# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml


trigger:
- master

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'

steps:

# INSTALL .NET SDK

- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '8.x'

# RESTORE .NET SOLUTION

- script: |
    dotnet restore WMS.sln
  displayName: 'Restore .NET Solution'



# BUILD .NET API

- script: |
    dotnet build WMS.sln --configuration $(buildConfiguration)
  displayName: 'Build .NET API'
- script: |
 

# RUN TESTS

- script: |
    dotnet test WMS.Tests/WMS.Tests.csproj
  displayName: 'Run Tests'




# INSTALL NODE.JS

- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Install Node.js'

# INSTALL ANGULAR PACKAGES

- script: |
    cd WMS.Frontend
    npm install
  displayName: 'Install Angular Packages'

# BUILD ANGULAR APP

- script: |
    cd WMS.Frontend
    npm run build
  displayName: 'Build Angular App'

# PUBLISH BUILD ARTIFACTS

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: '.'
    artifactName: 'WMS-Build'
  displayName: 'Publish Build Artifacts'